name: Build an empty package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare empty package content
        shell: bash
        run: |
          mkdir -p reports
          echo "placeholder" > reports/.placeholder

      - name: Create a zip package
        id: create_a_zip_package
        uses: OctopusDeploy/create-zip-package-action@v4
        with:
          package_id: DemoPackage
          version: 1.0.0
          output_folder: ./packaging
          base_path: reports
          files: |
            **/*.*



      - name: Push a package to Octopus Deploy 🐙
        id: push_a_package_to_octopus_deploy
        uses: OctopusDeploy/push-package-action@v4
        env:
          OCTOPUS_URL: https://myocto.octopus.app
          OCTOPUS_API_KEY: ${{ secrets.API_KEY }}
          OCTOPUS_SPACE: Default
        with:
          packages: |
            ./packaging/**/*.zip
                    